blog/urls.py
from . import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('<int:post_id>', views.detail, name='detail'),
]

portfolio/urls.py
from pfolio import views
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=200)
    contents = models.TextField()
    date = models.DateField(blank=True)

    def __str__(self):
        return self.title

pfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image=models.ImageField(upload_to='pfolio/images/')
    url = models.URLField(blank=True)

        
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def all_posts(request):
    posts = Post.objects.order_by('-date')
    return render(request, 'blog/all_posts.html', {'posts':posts})

def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/detail.html', {'post':post})

pfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'pfolio/home.html', {'projects':projects})

blog/templates/blog/all_posts.html
{% extends 'pfolio/base.html' %}

{% block content %}
    <h1>Richard Mateosian Blog</h1>

    <h2>({{ posts.count }} post{{ posts.count|pluralize }})</h2>

    {% for post in posts %}

        <a href="{% url 'blog:detail' post.id %}"><h2>{{ post.title }}</h2></a>

        <h3>{{ post.date | date:'D, j M Y' }}</h3>

        <p>{{ post.contents | safe | truncatechars:40 }}</p>

    {% endfor %}
{% endblock %}

blog/templates/blog/detail.html
{% extends 'pfolio/base.html' %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <h2>{{ post.date | date:'l, F jS Y' }}</h2>
    {{ post.contents | safe }}
{% endblock %}

pfolio/templates/pfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
      
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>


   {%block content %} {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

pfolio/templates/pfolio/home.html
{% extends 'pfolio/base.html' %}

{% block content %}
    {% load static %}

    <h1>Richard Mateosian Portfolio</h1>

    <h2><a href="{% url 'blog:all_posts' %}">Blog</a></h2>

    <img src="{% static 'pfolio/xrm.jpg' %}" style="max-width: 600px; height: auto; " >

    <h2><a href="{% static 'pfolio/Access_Winners_2019.pdf' %}">Sample PDF</a></h2>

    {% for project in projects %}

        <h2>{{ project.title }}</h2>

        <p>{{ project.description }}</p>

        <img src="{{ project.image.url }}" style="max-width: 150px; height: auto; " >

        {% if project.url %}

            <br><a href="{{ project.url }}">Link</a>

        {% endif %}
    {% endfor %}
{% endblock %}